#ifndef _MODELER_GLOBALS_H
#define _MODELER_GLOBALS_H

#ifndef M_PI
#define M_PI 3.141592653589793238462643383279502
#endif

// This is a list of the controls for the SampleModel
// We'll use these constants to access the values 
// of the controls from the user interface.
enum SampleModelControls
{ 
	XPOS, YPOS, ZPOS,
	LIGHT0_X, LIGHT0_Y, LIGHT0_Z, LIGHT0_DIFFUSE,
	LIGHT1_X, LIGHT1_Y, LIGHT1_Z, LIGHT1_DIFFUSE,
	ENABLE_LIGHT,
	HEAD_ROTATION_X, HEAD_ROTATION_Y, HEAD_ROTATION_Z,
	HEAD_WIDTH, HEAD_HEIGHT, HEAD_DEPTH,
	LEFT_UPPER_ARM_ROTATION_X, LEFT_UPPER_ARM_ROTATION_Y, LEFT_UPPER_ARM_ROTATION_Z,LEFT_LOWER_ARM_ROTATION_X,
	RIGHT_UPPER_ARM_ROTATION_X, RIGHT_UPPER_ARM_ROTATION_Y, RIGHT_UPPER_ARM_ROTATION_Z,RIGHT_LOWER_ARM_ROTATION_X,
	LEFT_UPPER_LEG_ROTATION_X, LEFT_UPPER_LEG_ROTATION_Y, LEFT_UPPER_LEG_ROTATION_Z,LEFT_LOWER_LEG_ROTATION_X, LEFT_FOOT_ROTATION_X,
	RIGHT_UPPER_LEG_ROTATION_X, RIGHT_UPPER_LEG_ROTATION_Y, RIGHT_UPPER_LEG_ROTATION_Z,RIGHT_LOWER_LEG_ROTATION_X, RIGHT_FOOT_ROTATION_X,
	
	WAIST_ROTATION_X, WAIST_ROTATION_Y, WAIST_ROTATION_Z,
	DRAW_LEVEL, DRAW_TEXTURE,
	DISPLAY_LSYSTEM, LSYSTEM_TYPE, LSYSTEM_ITER, LS_LENGTH,
	NUMCONTROLS
};

// Colors
#define COLOR_RED		1.0f, 0.0f, 0.0f
#define COLOR_GREEN		0.2f, 0.4f, 0.2f
#define COLOR_BLUE		0.0f, 0.0f, 1.0f
#define COLOR_YELLOW    1.0f, 1.0f, 0.5f
#define COLOR_CYAN		0.6f, 0.8f, 0.4f
#define COLOR_GRAY		0.5f, 0.5f, 0.5f
#define COLOR_BROWN		0.6f, 0.2f, 0.2f
#define COLOR_DARK		0.3f, 0.3f, 0.3f
#define COLOR_WHITE		1.0f, 1.0f, 1.0f
#define COLOR_PINK		1.0f, 0.5f, 0.5f
#define COLOR_SKIN		1.0f, 0.8f, 0.6f
#define COLOR_HAIR		1.0f, 0.6f, 0.2f
#define COLOR_DEC		0.4f, 0.4f, 0.2f
#define COLOR_WAIST		0.2f, 0.4f, 0.0f

// We'll be getting the instance of the application a lot; 
// might as well have it as a macro.
#define VAL(x) (ModelerApplication::Instance()->GetControlValue(x))

#endif